name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Check Clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Check Documentation Build
        run: cargo doc --no-deps --all-features
